12110161_Web/12110161_Web/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace _12110161_Web.Models
{
    public class Post
    {
        public int ID { get; set; }
        [Required]
        [StringLength(500, ErrorMessage = "Phải nhập 20--> 500 kí tự", MinimumLength = 6)]
        public string Title { get; set; }
        [Required]
        [StringLength(500, ErrorMessage = "Phải nhập 20--> 500 kí tự", MinimumLength = 4)]
        public string Sumary { get; set; }
        [Required]
        [StringLength(10000, ErrorMessage = "Tối thiểu 50 kí tự", MinimumLength = 50)]
        public string Body { get; set; }


        [DataType(DataType.DateTime)]
        public System.DateTime DayCreate { get; set; }


        public int UserProfileUserId { get; set; }
        public virtual UserProfile UserProfile { get; set; }

        public int TheLoaiID { get; set; }
        public virtual TheLoai TheLoai { get; set; }



        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}

12110161_Web/12110161_Web/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _12110161_Web.Models;

namespace _12110161_Web.Controllers
{
    public class CommentsController : Controller
    {
        private Web_12110161 db = new Web_12110161();

        //
        // GET: /Comments/

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Post);
            return View(comments.ToList());
        }

        //
        // GET: /Comments/Details/5

        public ActionResult Details(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // GET: /Comments/Create

        public ActionResult Create()
        {
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title");
            return View();
        }

        //
        // POST: /Comments/Create

        [HttpPost]
        public ActionResult Create(Comment comment,int idpost)
        {
            if (ModelState.IsValid)
            {
                comment.PostID = idpost;
                comment.DayCreate = DateTime.Now;
                db.Comments.Add(comment);
                db.SaveChanges();
                return PartialView("viewComment", comment);
                //return RedirectToAction("Details/" + idpost,"Post");
            }

            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // GET: /Comments/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // POST: /Comments/Edit/5

        [HttpPost]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.DayCreate = DateTime.Now;
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // GET: /Comments/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comments/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

12110161_Web/12110161_Web/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _12110161_Web.Models;

namespace _12110161_Web.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private Web_12110161 db = new Web_12110161();

        //
        // GET: /Post/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.UserProfile).Include(p => p.TheLoai);
            return View(posts.ToList());
        }

        //
        // GET: /Post/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewData["idpost"] = id;
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            ViewBag.TheLoaiID = new SelectList(db.TheLoais, "ID", "TenTheLoai");
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        public ActionResult Create(Post post,string Content)
        {
            if (ModelState.IsValid)
            {
                post.DayCreate = DateTime.Now;

                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName })
                    .Where(y => y.UserName == User.Identity.Name).Single().UserId;
                post.UserProfileUserId = userid;

                
                // Tạo list tag cho Post
                List<Tag> Tags = new List<Tag>();
                // Tách các tag bằng dấu phẩy
                string[] TagContent = Content.Split(',');
                // lặp các tag vừa tách
                foreach (string item in TagContent)
                {
                    // Tìm xem các tag có hay chưa
                    Tag tagExits = null;
                    var ListTag = db.Tags.Where(y => y.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {

                        tagExits = ListTag.First();
                        tagExits.Posts.Add(post);
                    }
                    else
                    {
                        tagExits = new Tag();
                        tagExits.Content = item;
                        tagExits.Posts = new List<Post>();
                        tagExits.Posts.Add(post);
                    }

                    Tags.Add(tagExits);
                }
                // gán list tag vào post
                post.Tags = Tags;

                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            ViewBag.TheLoaiID = new SelectList(db.TheLoais, "ID", "TenTheLoai", post.TheLoaiID);
            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            ViewBag.TheLoaiID = new SelectList(db.TheLoais, "ID", "TenTheLoai", post.TheLoaiID);
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        public ActionResult Edit(Post post,string Content)
        {
            if (ModelState.IsValid)
            {
                post.DayCreate = DateTime.Now;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName })
                    .Where(y => y.UserName == User.Identity.Name).Single().UserId;
                post.UserProfileUserId = userid;

                // Tạo list tag cho Post
                List<Tag> Tags = new List<Tag>();
                // Tách các tag bằng dấu phẩy
                string[] TagContent = Content.Split(',');
                // lặp các tag vừa tách
                foreach (string item in TagContent)
                {
                    // Tìm xem các tag có hay chưa
                    Tag tagExits = null;
                    var ListTag = db.Tags.Where(y => y.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {

                        tagExits = ListTag.First();
                        tagExits.Posts.Add(post);
                    }
                    else
                    {
                        tagExits = new Tag();
                        tagExits.Content = item;
                        tagExits.Posts = new List<Post>();
                        tagExits.Posts.Add(post);
                    }

                    Tags.Add(tagExits);
                }
                // gán list tag vào post
                post.Tags = Tags;

                db.Posts.Add(post);
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            ViewBag.TheLoaiID = new SelectList(db.TheLoais, "ID", "TenTheLoai", post.TheLoaiID);
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

12110161_Web/12110161_Web/Views/Post/Create.cshtml
@model _12110161_Web.Models.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Sumary)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Sumary)
            @Html.ValidationMessageFor(model => model.Sumary)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        
        <div class="editor-label">
            @Html.LabelFor(model => model.TheLoaiID, "TheLoai")
        </div>
        <div class="editor-field">
            @Html.DropDownList("TheLoaiID", String.Empty)
            @Html.ValidationMessageFor(model => model.TheLoaiID)
        </div>
        <div class="editor-label">
            Tag:
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => new _12110161_Web.Models.Tag().Content)
            @Html.ValidationMessageFor(model => new _12110161_Web.Models.Tag().Content)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

12110161_Web/12110161_Web/Views/Post/Delete.cshtml
@model _12110161_Web.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Sumary)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Sumary)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DayCreate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DayCreate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TheLoai.TenTheLoai)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TheLoai.TenTheLoai)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

12110161_Web/12110161_Web/Views/Post/Details.cshtml
@model _12110161_Web.Models.Post

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<hr />
<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Sumary)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Sumary)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DayCreate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DayCreate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfile.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TheLoai.TenTheLoai)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TheLoai.TenTheLoai)
    </div>
</fieldset>
<h3>Tags</h3>
<hr />
<fieldset>
    <legend>Tags</legend>
    @foreach(var item in Model.Tags)
    {
        <div class="display-field">
            @Html.DisplayFor(x=>item.Content)
        </div>
    }
</fieldset>

@Html.Partial("_AddComment",new _12110161_Web.Models.Comment(), ViewData )

<h3>Bình luận gần đây</h3>
<hr />
<fieldset>
    <legend>Comments</legend>
    <div id="result">
        @foreach (var cm in Model.Comments.OrderByDescending(x => x.DayCreate).Take(10))
        { 
            <div class="dislay-field">
                <h2 style="font-family: 'Times New Roman'; font-size: 16px; font-weight: bold;">Tạo cách đây: @Html.DisplayFor(c => cm.LastTime) phút trước.
                </h2>
            </div>
            <div class="dislay-field">
                <h2 style="font-family: 'Times New Roman'; font-size: 16px;">
                    @Html.DisplayFor(c => cm.Body)
                </h2>
            </div>
        }
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

12110161_Web/12110161_Web/Views/Post/Edit.cshtml
@model _12110161_Web.Models.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Sumary)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Sumary)
            @Html.ValidationMessageFor(model => model.Sumary)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        

        <div class="editor-label">
            @Html.LabelFor(model => model.TheLoaiID, "TheLoai")
        </div>
        <div class="editor-field">
            @Html.DropDownList("TheLoaiID", String.Empty)
            @Html.ValidationMessageFor(model => model.TheLoaiID)
        </div>
        <div class="editor-label">
            Tag:
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => new _12110161_Web.Models.Tag().Content)
            @Html.ValidationMessageFor(model => new _12110161_Web.Models.Tag().Content)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

12110161_Web/12110161_Web/Views/Post/Index.cshtml
@model IEnumerable<_12110161_Web.Models.Post>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sumary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DayCreate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserProfile.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TheLoai.TenTheLoai)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sumary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Body)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DayCreate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserProfile.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TheLoai.TenTheLoai)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

12110161_Web/12110161_Web/Views/Post/_AddComment.cshtml
@model _12110161_Web.Models.Comment

@{
    ViewBag.Title = "_AddComment";
}
@using (Html.BeginForm("Create", "Comments", FormMethod.Post, new { id="my-comment"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add Comment</legend>
       <div class="editor-field">
               @Html.EditorFor(model => model.Body)
               @Html.ValidationMessageFor(model => model.Body)
       </div>  
        @Html.Hidden("idpost",ViewData["idpost"])
       <p>
           <input type="submit" value="Comment" />
        </p>
    </fieldset>
}
<script src="~/Scripts/addComment.js"></script>