12110161_Web/12110161_Web/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _12110161_Web.Models;

namespace _12110161_Web.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private Web_12110161 db = new Web_12110161();

        //
        // GET: /Post/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.UserProfile).Include(p => p.TheLoai);
            return View(posts.ToList());
        }

        //
        // GET: /Post/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewData["idpost"] = id;
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            ViewBag.TheLoaiID = new SelectList(db.TheLoais, "ID", "TenTheLoai");
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        public ActionResult Create(Post post,string Content)
        {
            if (ModelState.IsValid)
            {
                post.DayCreate = DateTime.Now;

                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName })
                    .Where(y => y.UserName == User.Identity.Name).Single().UserId;
                post.UserProfileUserId = userid;

                
                // Tạo list tag cho Post
                List<Tag> Tags = new List<Tag>();
                // Tách các tag bằng dấu phẩy
                string[] TagContent = Content.Split(',');
                // lặp các tag vừa tách
                foreach (string item in TagContent)
                {
                    // Tìm xem các tag có hay chưa
                    Tag tagExits = null;
                    var ListTag = db.Tags.Where(y => y.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {

                        tagExits = ListTag.First();
                        tagExits.Posts.Add(post);
                    }
                    else
                    {
                        tagExits = new Tag();
                        tagExits.Content = item;
                        tagExits.Posts = new List<Post>();
                        tagExits.Posts.Add(post);
                    }

                    Tags.Add(tagExits);
                }
                // gán list tag vào post
                post.Tags = Tags;

                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            ViewBag.TheLoaiID = new SelectList(db.TheLoais, "ID", "TenTheLoai", post.TheLoaiID);
            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            ViewBag.TheLoaiID = new SelectList(db.TheLoais, "ID", "TenTheLoai", post.TheLoaiID);
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        public ActionResult Edit(Post post,string Content)
        {
            if (ModelState.IsValid)
            {
                post.DayCreate = DateTime.Now;
                int userid = db.UserProfiles.Select(x => new { x.UserId, x.UserName })
                    .Where(y => y.UserName == User.Identity.Name).Single().UserId;
                post.UserProfileUserId = userid;

                // Tạo list tag cho Post
                List<Tag> Tags = new List<Tag>();
                // Tách các tag bằng dấu phẩy
                string[] TagContent = Content.Split(',');
                // lặp các tag vừa tách
                foreach (string item in TagContent)
                {
                    // Tìm xem các tag có hay chưa
                    Tag tagExits = null;
                    var ListTag = db.Tags.Where(y => y.Content.Equals(item));
                    if (ListTag.Count() > 0)
                    {

                        tagExits = ListTag.First();
                        tagExits.Posts.Add(post);
                    }
                    else
                    {
                        tagExits = new Tag();
                        tagExits.Content = item;
                        tagExits.Posts = new List<Post>();
                        tagExits.Posts.Add(post);
                    }

                    Tags.Add(tagExits);
                }
                // gán list tag vào post
                post.Tags = Tags;

                db.Posts.Add(post);
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            ViewBag.TheLoaiID = new SelectList(db.TheLoais, "ID", "TenTheLoai", post.TheLoaiID);
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

12110161_Web/12110161_Web/Views/Shared/CacTrangLink.cshtml
<div>
    <h3>Các trang liên kết
    </h3>

    <hr>
    <ul>

        <li>

            <a  href="http://bongdaplus.vn/" target="_blank">bongdaplus.vn</a>
        </li>
        <li>
            <a href="http://hcm.24h.com.vn/bong-da-c48.html" target="_blank">24h.com.vn</a>
        </li>
        <li>
            <a href="http://topbongda.com/" target="_blank">topbongda.com</a>
        </li>
        <li>
            <a href="http://bongda24h.vn/index.html" target="_blank">bongda24h.vn</a>
        </li>
        <li>
            <a href="http://vnbongda.vn/" target="_blank">vnbongda.vn</a>
        </li>
        <li>
            <a href="https://vn.news.yahoo.com/thethao/" target="_blank">vn.news.yahoo.com</a>
        </li>
        <li>
            <a href="http://thethao.vtv.vn/" target="_blank">thethao.vtv.vn</a>
        </li>
        <li>
            <a href="http://thethaovanhoa.vn/" target="_blank">thethaovanhoa.vn</a>
        </li>
        <li>
            <a href="http://bongdaso.us/" target="_blank">bongdaso.us</a>
        </li>
        <li>
            <a href="http://thethao247.vn/" target="_blank">thethao247.vn</a>
        </li>
        <li>
            <a href="http://thethao.tuoitre.vn/trang/bong-da" target="_blank">thethao.tuoitre.vn</a>
        </li>
        <li>
            <a href="http://tinthethao.com.vn/" target="_blank">tinthethao.com.vn</a>
        </li>
        <li>
            <a href="http://bongdatv.net/" target="_blank">bongdatv.net</a>
        </li>
        <li>
            <a href="http://ibongda.vn/" target="_blank">ibongda.vn</a>
        </li>
        <li>
            <a href="http://dantri.com.vn/the-thao.htm" target="_blank">dantri.com.vn</a>
        </li>
        <li>
            <a href="http://bongda.com.vn/" target="_blank">bongda.com.vn</a>
        </li>

    </ul>
</div>

12110161_Web/12110161_Web/Views/Shared/Footer.cshtml
<pre style="font-family:Times New Roman; font-size:16px;">
    Công ty phát triển phần mềm GobalDevelop
    Địa chỉ: 41/3, Đặng Văn Bi, phường Trường Thọ, Quận Thủ Đức
    Điện Thoại: 01684147047
    Email:thanhsang972@gmail.com
</pre>

12110161_Web/12110161_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
    </head>
    <body>
        
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("BongDaTongHop.Com", "Index", "Post")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            @*<li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                            <li>@Html.ActionLink("ĐăngBài", "Create", "Post")</li>
                            @*<li>@Html.ActionLink("XemBài", "Index", "Post")</li>*@
                        </ul>
                    </nav>
                </div>
            </div>
        </header>


        <div id="body">
            <hr />
            <nav class="mainMenu">
                <ul id="menuTheLoai">
                    <li>@Html.ActionLink("Home", "Index", "Post")</li>
                    <li><a href="http://localhost:64909/Menu/Details/5" >Việt Nam</a></li>
                    <li><a href="http://localhost:64909/Menu/Details/2" >Champion League</a></li>
                    <li><a href="http://localhost:64909/Menu/Details/1" >Anh</a></li>
                    <li><a href="http://localhost:64909/Menu/Details/4" >Tây Ban Nha</a></li>
                    <li><a href="http://localhost:64909/Menu/Details/7" >Đức</a></li>
                    <li><a href="http://localhost:64909/Menu/Details/6" >Italia</a></li>
                    <li><a href="http://localhost:64909/Menu/Details/3" >Pháp</a></li>
                    
                </ul>
            </nav>
            <hr />
            @RenderSection("featured", required: false)
            @RenderBody()
            
        </div>

        @Html.Partial("CacTrangLink")

        <footer>
            @Html.Partial("Footer")
        </footer>

        
        @RenderSection("scripts", required: false)
    </body>
</html>